[SW-0] compat: use vm_flags_set() to set vm flags
Accessing the vm flags directly leads to a compilation error in latest
kernel:
error: assignment of read-only member ‘vm_flags’

Back-port the vm_flags_set() function which was added to modify these
flags.

Change-Id: I8363962d8c19b5323adbc52555fc3f59efd3ae01
Signed-off-by: Tomer Tayar <ttayar@habana.ai>