[SW-142076] importer: mark hl_importer_reg_user_mr_dmabuf() as static
Fix the following compilation error:

error: no previous prototype for ‘hl_importer_reg_user_mr_dmabuf’
[-Werror=missing-prototypes]

Change-Id: I8d87a43a8600b34756027f876f70e7ed73635026
Signed-off-by: Tomer Tayar <ttayar@habana.ai>